In [2]:
from operator import imod

inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [
    inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1,
    inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,
    inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3,
]
print(output)


[4.8, 1.21, 2.385]


In [6]:
import numpy as np

result = 0.10 * np.random.randn(2, 1)
print(result)

[[0.07987094]
 [0.10362028]]


In [8]:
import numpy as np

inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],  # weights of the first output neuron
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases
print(output)



[4.8   1.21  2.385]


In [9]:

inputs = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [  # shape (3*4): number of neurons by number of inputs
    [0.2, 0.8, -0.5, 1.0],  # weights of the first output neuron
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [1]:
import numpy as np

X = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]


class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        """
        :param n_inputs: number of inputs
        :param n_neurons: numbers of output neurons
        """
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


layer1 = LayerDense(n_inputs=4, n_neurons=5)
layer2 = LayerDense(n_inputs=5, n_neurons=2)
layer1.forward(X)
print(layer1.output, end="\n")
layer2.forward(layer1.output)
print(layer2.output)



[[ 0.29287968 -0.15167961 -0.33642011  0.70848216 -0.60096422]
 [-0.01032037  0.18387023 -0.24139145 -0.41923367  0.15995583]
 [ 0.23675338  0.27169149 -0.33737071  0.56840999 -0.65906962]]
[[ 0.01776217 -0.03240104]
 [-0.01366881  0.02308479]
 [ 0.06919029 -0.05629207]]


In [3]:
# Rectified Linear
class ActivationReLU:

    def forward(self, inputs):
        self.output = np.maximum(0, inputs)



In [4]:
import nnfs
from nnfs.datasets import spiral_data

# nnfs.init()

# X stands for input, y is the target/output
X, y = spiral_data(100, 3)

layer1 = LayerDense(n_inputs=2, n_neurons=5)
activation1 = ActivationReLU()

layer1.forward(X)
activation1.forward(layer1.output)

print(layer1.output)
# print(activation1.output)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 3.33144789e-04 -1.10949556e-03  3.75460909e-04 -6.12334789e-05
  -8.94310733e-05]
 [ 7.11515867e-04 -2.79743175e-03  9.43529401e-04  1.41243925e-03
   8.60468849e-04]
 ...
 [-3.42467201e-02  1.37300515e-01 -4.62927820e-02 -7.75583885e-02
  -4.79399107e-02]
 [-2.12337766e-02  1.15772199e-01 -3.88473445e-02 -1.58621097e-01
  -1.05035545e-01]
 [-3.01163585e-02  1.38057039e-01 -4.64422588e-02 -1.30665331e-01
  -8.47158183e-02]]
