In [2]:
from operator import imod

inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [
    inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1,
    inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,
    inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3,
]
print(output)


[4.8, 1.21, 2.385]


In [6]:
import numpy as np

result = 0.10 * np.random.randn(2, 1)
print(result)

[[0.07987094]
 [0.10362028]]


In [8]:
import numpy as np

inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],  # weights of the first output neuron
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases
print(output)



[4.8   1.21  2.385]


In [9]:

inputs = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [  # shape (3*4): number of neurons by number of inputs
    [0.2, 0.8, -0.5, 1.0],  # weights of the first output neuron
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [12]:
import numpy as np

X = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        """
        :param n_inputs: number of inputs
        :param n_neurons: numbers of output neurons
        """
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


layer1 = LayerDense(n_inputs=4, n_neurons=5)
layer2 = LayerDense(n_inputs=5, n_neurons=2)
layer1.forward(X)
# print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)


[[-0.04153169  0.10387514]
 [-0.04830495 -0.11999407]
 [-0.05324831  0.15169788]]
