In [11]:
import numpy as np

tensor = np.array([[[
    [
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
    ],
    [
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
    ]
]]])

# dimension: what is the depth we need to go to access one element
print(tensor.ndim)
# shape: size in each dimension
print(tensor.shape)
# size: total number of elements
print(tensor.size)
print(tensor[0][0][0][0][0])


5
(1, 1, 2, 3, 4)
24
1


In [2]:
import numpy as np

# if both arguments are 1-d array, dot product returns scalar value
product = np.dot([1, 2, 3], [1, 2, 3])
print(product)

mat = np.array([[3], [2], [1]])
print(mat.shape)

# multiplication is allowed between (k,) and (k,x)
# multiplication between (3,) and (3,1)
product = np.dot([1, 2, 3], mat)
print(product)

# multiplication between (1,) and (1,3)
product = np.dot([3], [[3, 2, 1]])
print(product)


14
(3, 1)
[10]
[9 6 3]


In [5]:

input = np.array([[3], [2], [1]])
print(input.shape)


(3, 1)


In [5]:
import numpy as np

mat = [
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 9]
]

dot = np.dot(3, mat)
print(dot)

print(np.dot([1, 2, 3], mat))


[[ 3  6  9]
 [ 9 12 15]
 [18 21 27]]
[25 31 40]
